### ISSUE TITLE
add the other options

### ISSUE THREAD

**Issue by xenoterracide** [Youssef93/fast-clean#5]
> '' (empty strings)
> {} (empty objects)
> [] (empty arrays)

any chance you would add the options to not do these? there may be reasons to send them IMO. Also it is not obvious whether null cleaner is `null` or `nullish` meaning null or undefined. There is also reasons to transmit `null`

currently it looks like this project is unmaintained

**Comment by Youssef93** [comment]
- undefined values get removed by default, so if the `nullCleaner` option is set, it will remove `null` values, otherwise they will not be cleaned.
- As for the other concerns, they were always part of the plan to be added later.
  It's not that the project is unmaintained  but rather it did not pick up & I never needed to add these features in current use cases. However if that's something that you need I'd be happy to add it.

**Comment by xenoterracide** [comment]
yes, I'm using clean-deep atm. Here's how I'm using it

```ts
export function stripUndefined<T>(object: T, schema: Joi.AnySchema<T>): T {
  const cleaned = cleanDeep(object, {
    nullValues: false,
    emptyArrays: false,
    emptyObjects: false,
    emptyStrings: false,
    NaNValues: true,
  }) as T
  return validateWith<T>(cleaned, schema, { stripUnknown: true })
}
```

in actuality, I also need to be able to do a skip list, I'd like to be able to return the same type I'm sending, I'm trying to discard keys that have undefined values only. I think that the type-ing more or less should be possible, and even safe given what some utils like ts-essentials can do. I haven't fully worked out how to do it though.

**Comment by xenoterracide** [comment]
obviously I'm wrapping clean-deep to do that type casting, but re-validating an object is kind of annoying.

**Comment by Youssef93** [comment]
Thanks for using the module.
Version 1.2.0 is now released on npm that supports adding the additional options. Please check the docs [here](https://github.com/Youssef93/fast-clean#options)

**Comment by Youssef93** [comment]
fixed in https://github.com/Youssef93/fast-clean/pull/7
